fixing CI

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -140,12 +140,31 @@ jobs:
         run: dist/ubuntu/build.sh -DLIBSTORED_DOCUMENTATION=ON -DLIBSTORED_PYLIBSTORED=ON -DLIBSTORED_HAVE_ZTH=ON
 
   # Dummy job that depends on all other build-* jobs.
-  build-all:
+  build-all-check:
     needs: [build-ubuntu, build-ubuntu-prev, build-windows, build-mac, build-mingw, test-documentation]
     runs-on: ubuntu-latest
+    if: success()
+    outputs:
+      success: ${{ steps.setoutput.outputs.success }}
     steps:
-      - name: done
-        run: echo 'Completed all build jobs.'
+      - id: setoutput
+        run: echo "::set-output name=success::true"
+
+  # Dummy job to check if build-all-check was successful.
+  build-all:
+    needs: [build-ubuntu, build-ubuntu-prev, build-windows, build-mac, build-mingw, test-documentation, build-all-check]
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - run: |
+          passed="${{ needs.build-all-check.outputs.success }}"
+          if [[ $passed == "true" ]]; then
+            echo "Build passed"
+            exit 0
+          else
+            echo "Build failed"
+            exit 1
+          fi
 
   # If everything is OK, publish documentation
   documentation:
